import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/cartContext/CartContext";
import Footer from "@/components/footer/page";
import MySessionProvider from "@/components/MYSessionProvider/MySessionProvider";
import WishListContextProvider from "@/components/wishListContext/WishListContext";
import AddressContextProvider from "@/components/addressContext/AddressContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <MySessionProvider>
<CartContextProvider>
  <WishListContextProvider>
    <AddressContextProvider>
      <Navbar/>
      <div className="container mx-auto">
 {children}
 <Toaster/>
      </div>
      <Footer/>


    </AddressContextProvider>

  </WishListContextProvider>
        
      </CartContextProvider>
        </MySessionProvider>
      
      
      </body>
    </html>
  );
}
